services:
  mongo:
    image: mongo:7
    container_name: bootcamp_auth_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bootcamp
      MONGO_INITDB_ROOT_PASSWORD: bootcamp123
      MONGO_INITDB_DATABASE: bootcamp_auth_dev
    volumes:
      - mongo_auth_data:/data/db

volumes:
  mongo_auth_data:
